// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnqzXKIEzxbyrIMuhuKV0Y1Z_p6BLWNyc',
    appId: '1:472404132878:web:20cfc2a390a7339e49e85f',
    messagingSenderId: '472404132878',
    projectId: 'examination-room-scheduling',
    authDomain: 'examination-room-scheduling.firebaseapp.com',
    storageBucket: 'examination-room-scheduling.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEgCVBbSfUhIQWOuc3YMvBmPXaq2ASr8',
    appId: '1:472404132878:android:9db3ddfbbfc2b60649e85f',
    messagingSenderId: '472404132878',
    projectId: 'examination-room-scheduling',
    storageBucket: 'examination-room-scheduling.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE750h8qnsjjEcsT4TiLwAetGQL5bqZxE',
    appId: '1:472404132878:ios:eb27a3c504a5cab149e85f',
    messagingSenderId: '472404132878',
    projectId: 'examination-room-scheduling',
    storageBucket: 'examination-room-scheduling.appspot.com',
    iosBundleId: 'com.roomexaminationscheduler.roomexaminationschedulingsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE750h8qnsjjEcsT4TiLwAetGQL5bqZxE',
    appId: '1:472404132878:ios:eb27a3c504a5cab149e85f',
    messagingSenderId: '472404132878',
    projectId: 'examination-room-scheduling',
    storageBucket: 'examination-room-scheduling.appspot.com',
    iosBundleId: 'com.roomexaminationscheduler.roomexaminationschedulingsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnqzXKIEzxbyrIMuhuKV0Y1Z_p6BLWNyc',
    appId: '1:472404132878:web:0f8bd18b897a064149e85f',
    messagingSenderId: '472404132878',
    projectId: 'examination-room-scheduling',
    authDomain: 'examination-room-scheduling.firebaseapp.com',
    storageBucket: 'examination-room-scheduling.appspot.com',
  );
}
